/**
 * Push notifications (Firebase Cloud Messaging).
 *
 * The registration token is generated by the browser at runtime — nothing here
 * contains or expects a hard-coded token — and is stored against the signed-in
 * user's device record. Permission is requested from an explicit user action
 * (never on load), and every failure degrades to in-app notifications only.
 *
 * Requires `VITE_FIREBASE_VAPID_KEY` (the web push certificate from project
 * settings) plus messaging service configuration. Without them the UI shows the
 * requirement instead of pretending push works.
 */

import { app, integrations } from '@/config/env';
import { AppError, toAppError } from '@/lib/errors';
import { newId } from '@/lib/ids';
import { services } from '@/services/session-store';
import type { AppNotification, DeviceToken } from '@/types/domain';

export type PushPermission = 'unsupported' | 'default' | 'granted' | 'denied' | 'not-configured';

export const pushSupported = (): boolean => typeof window !== 'undefined' && 'Notification' in window;

export const currentPermission = (): PushPermission => {
  if (!integrations.push.configured) return 'not-configured';
  if (!pushSupported()) return 'unsupported';
  return Notification.permission as PushPermission;
};

const serviceWorker = async (): Promise<ServiceWorkerRegistration | null> => {
  if (!('serviceWorker' in navigator)) return null;
  try {
    return await navigator.serviceWorker.register('/firebase-messaging-sw.js', { scope: '/' });
  } catch (error) {
    throw new AppError(
      'The notification service worker could not be registered. Check that the site is served over HTTPS.',
      'CONFIGURATION',
    );
  }
};

async function requestBrowserToken(): Promise<string> {
  const { getMessaging, getToken } = await import('firebase/messaging');
  const { getFirebaseApp } = await import('@/services/firebase/app');
  const registration = await serviceWorker();
  if (!registration) throw new AppError('This browser does not support background push messages.', 'UNSUPPORTED_FILE');
  return getToken(getMessaging(getFirebaseApp()), { vapidKey: app.fcmVapidKey, serviceWorkerRegistration: registration });
}

export interface PushStatus {
  state: PushPermission;
  registered: number;
  tokenPreview: string | null;
  lastError: string | null;
}

export async function enablePush(): Promise<{ token: string; recordId: string }> {
  const registry = services();
  const actor = registry.require();
  if (registry.provider.kind !== 'firebase') {
    throw new AppError(
      'Push delivery needs Firebase Cloud Messaging, which is only available in a Firebase deployment. In-app reminders and SMS (when configured) continue to work.',
      'CONFIGURATION',
    );
  }
  if (!app.fcmVapidKey) {
    throw new AppError(
      'Push is not configured for this deployment. Set VITE_FIREBASE_VAPID_KEY to the project web push certificate.',
      'CONFIGURATION',
    );
  }

  try {
    const permission = await Notification.requestPermission();
    if (permission !== 'granted') {
      throw new AppError('Notifications are blocked in this browser. Allow them in site settings and try again.', 'FORBIDDEN');
    }
    const token = await requestBrowserToken();
    const devices = await registry.data.list('devices', { where: [{ field: 'userId', op: '==', value: actor.uid }] });
    const existing = devices.rows.find((device) => device.token === token);
    const recordId = existing?.id ?? newId('dev');
    const payload: DeviceToken = {
      id: recordId,
      userId: actor.uid,
      token,
      platform: navigator.userAgent.includes('Android') ? 'android' : navigator.userAgent.includes('iPhone') ? 'ios' : 'web',
      userAgent: navigator.userAgent.slice(0, 120),
      permission: 'granted',
      createdAt: existing?.createdAt ?? new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      lastSeenAt: new Date().toISOString(),
    };
    if (existing) {
      await registry.data.update('devices', recordId, payload as Partial<DeviceToken>);
    } else {
      await registry.data.create('devices', payload as never).catch(() => null);
    }
    await registry.data.audit('user.push_token_registered', 'user', actor.uid, {
      metadata: { platform: payload.platform, deviceId: recordId },
    });
    return { token, recordId };
  } catch (error) {
    throw toAppError(error, 'We could not switch on notifications for this device. Please try again.');
  }
}

export async function disablePush(recordId?: string): Promise<void> {
  const registry = services();
  const actor = registry.require();
  const devices = await registry.data.list('devices', { where: [{ field: 'userId', op: '==', value: actor.uid }] });
  const targets = recordId ? devices.rows.filter((device) => device.id === recordId) : devices.rows;
  for (const device of targets) {
    await registry.data.remove('devices', device.id).catch(() => null);
  }
  // The browser token itself is left in place: unsubscribing Cloudinary-side is
  // not possible, and Firestore removal stops all further sends to it.
}

export async function pushStatus(): Promise<PushStatus> {
  const registry = services();
  const actor = await registry.provider.list(
    'devices',
    { where: [{ field: 'userId', op: '==', value: registry.actorRef()?.uid ?? '' }] },
    registry.actorRef(),
  );
  const first = actor.rows[0];
  return {
    state: currentPermission(),
    registered: actor.rows.length,
    tokenPreview: first ? `${first.token.slice(0, 10)}…${first.token.slice(-4)}` : null,
    lastError: null,
  };
}

/**
 * In-app inbox. Push is an extra channel on top of this; a notification is always
 * written to the database first so nothing is lost when a device is offline.
 */
export async function listNotifications(options: { unreadOnly?: boolean } = {}): Promise<AppNotification[]> {
  const registry = services();
  const actor = registry.require();
  const { rows } = await registry.data.list('notifications', {
    where: [{ field: 'userId', op: '==', value: actor.uid }],
    orderBy: { field: 'sentAt', direction: 'desc' },
    limit: 100,
  });
  return rows.filter((row) => (options.unreadOnly ? !row.readAt : true));
}

export async function markNotificationRead(id: string): Promise<void> {
  const registry = services();
  await registry.data.update('notifications', id, { readAt: new Date().toISOString() } as Partial<AppNotification>);
}

export async function markAllNotificationsRead(): Promise<number> {
  const registry = services();
  const unread = await listNotifications({ unreadOnly: true });
  await Promise.all(unread.map((item) => markNotificationRead(item.id).catch(() => null)));
  return unread.length;
}

/** Sends an announcement to a facility team (supervisor/admin only). */
export async function sendAnnouncement(input: {
  title: string;
  body: string;
  facilityId: string | null;
  userIds?: string[];
  link?: string;
}): Promise<{ recipients: number; channels: string }> {
  const registry = services();
  const actor = registry.require();
  if (actor.role !== 'ADMIN' && actor.role !== 'FACILITY_SUPERVISOR') {
    throw new AppError('Only supervisors and administrators can send announcements.', 'FORBIDDEN');
  }
  if (input.facilityId && actor.role === 'FACILITY_SUPERVISOR' && actor.facilityId !== input.facilityId) {
    throw new AppError('Supervisors can only announce to their own facility.', 'FORBIDDEN');
  }

  const recipients = input.userIds?.length
    ? input.userIds
    : (
        await registry.data.list('users', {
          where: input.facilityId ? [{ field: 'facilityId', op: '==', value: input.facilityId }, { field: 'status', op: '==', value: 'ACTIVE' }] : [],
          limit: 200,
        })
      ).rows
        .filter((user) => user.status === 'ACTIVE' && user.id !== actor.uid)
        .map((user) => user.id);

  if (recipients.length === 0) {
    throw new AppError('No recipients matched. Choose a facility with active users.', 'VALIDATION');
  }

  for (const userId of recipients.slice(0, 200)) {
    await registry.data
      .notify({
        userId,
        kind: 'ANNOUNCEMENT',
        title: input.title,
        body: input.body,
        level: 'info',
        link: input.link ?? null,
        facilityId: input.facilityId,
      })
      .catch(() => null);
  }

  await registry.data.audit('notification.sent', 'notification', `announcement_${Date.now()}`, {
    facilityId: input.facilityId,
    metadata: { recipients: recipients.length, kind: 'announcement' },
  });

  return {
    recipients: Math.min(recipients.length, 200),
    channels: integrations.push.configured ? 'in-app + push (queued by device)' : 'in-app only',
  };
}
