/**
 * Built-in education library.
 *
 * These articles ship with the app so a mother has reliable content on the first
 * run, offline, with no database write. Administrators and providers can add,
 * edit and publish their own articles in Firestore; the two sources are merged at
 * read time (`services/content/articles.ts`) and a database article with the same
 * slug replaces the built-in one.
 *
 * Editorial rules this library follows, and that the admin editor repeats:
 *  • Plain, short sentences — the app is read on a phone, often in a hurry.
 *  • Never diagnose, never prescribe, never give a dose.
 *  • Every warning sign ends at "contact a healthcare professional" or "go now".
 *  • Content should be reviewed by a qualified maternal-health professional
 *    before publication; `reviewedBy` records who did that.
 */

import type { Article, ArticleBlock, ArticleCategory } from '@/types/domain';

const p = (text: string): ArticleBlock => ({ type: 'paragraph', text });
const h = (text: string, level: 2 | 3 = 2): ArticleBlock => ({ type: 'heading', text, level });
const ul = (items: string[]): ArticleBlock => ({ type: 'list', items });
const ol = (items: string[]): ArticleBlock => ({ type: 'list', items, ordered: true });
const note = (text: string, tone: 'info' | 'warning' | 'danger' = 'info'): ArticleBlock => ({ type: 'note', text, tone });

interface Seed {
  slug: string;
  title: string;
  summary: string;
  category: ArticleCategory;
  week?: number;
  tags: string[];
  minutes: number;
  blocks: ArticleBlock[];
}

const SEE_A_PROVIDER =
  'Mama Care gives educational information. It does not diagnose conditions or replace a qualified healthcare professional. If you are worried about your health or your baby\'s health, contact a provider. In an emergency, seek medical assistance immediately.';

export const ARTICLE_SEEDS: Seed[] = [
  {
    slug: 'first-antenatal-visit',
    title: 'Your first antenatal visit',
    summary: 'What happens at a booking visit, what to bring, and why going early matters.',
    category: 'antenatal-care',
    week: 8,
    tags: ['antenatal', 'first visit'],
    minutes: 4,
    blocks: [
      p('Antenatal care is the care you receive from a health worker while you are pregnant. Going early — ideally before 12 weeks — gives your provider time to check your health, find out anything that needs extra attention, and plan the rest of your pregnancy with you.'),
      h('What usually happens'),
      ul([
        'Questions about your health, your previous pregnancies, any medicines you take and your family history.',
        'Weight, height and blood pressure measured.',
        'Blood tests: your blood group, haemoglobin (to check for anaemia), HIV and syphilis testing, and others offered locally.',
        'A urine test.',
        'An examination of your belly, and sometimes an ultrasound scan.',
        'Tetanus toxoid vaccination if you need it.',
        'Advice on supplements, malaria prevention and nutrition.',
      ]),
      h('What to take with you'),
      ul(['Your health card or any previous records.', 'A list of the medicines and supplements you take.', 'Your questions — write them down beforehand.', 'Someone to support you, if you would like company.']),
      note('You can ask questions at any point. No question about your pregnancy is a silly question.'),
      p(SEE_A_PROVIDER),
    ],
  },
  {
    slug: 'antenatal-visit-schedule',
    title: 'How many antenatal visits do you need?',
    summary: 'The World Health Organization recommends at least eight contacts during pregnancy.',
    category: 'antenatal-care',
    tags: ['antenatal', 'appointments'],
    minutes: 3,
    blocks: [
      p('WHO recommends at least eight antenatal contacts. This reduces the chance of a problem being missed and gives you more chances to ask questions.'),
      ol([
        'First contact: as early as possible, ideally before 12 weeks.',
        '20 weeks.',
        '26 weeks.',
        '30 weeks.',
        '34 weeks.',
        '36 weeks.',
        '38 weeks.',
        '40 weeks.',
      ]),
      p('Your provider may ask you to come more often if you need extra monitoring. Keep every appointment, even when you feel completely well — many important checks are done when nothing feels wrong.'),
      note('Use the Appointments screen to record each visit, and switch on reminders so you are told the day before.'),
      p(SEE_A_PROVIDER),
    ],
  },
  {
    slug: 'eating-well-in-pregnancy',
    title: 'Eating well in pregnancy',
    summary: 'What to eat, how much, and how to manage nausea and heartburn.',
    category: 'nutrition',
    week: 10,
    tags: ['nutrition', 'diet'],
    minutes: 5,
    blocks: [
      p('You do not need to eat twice as much. You need to eat a little more, and better, especially in the second and third trimesters.'),
      h('Build every meal around these'),
      ul([
        'Staple food: nshima, rice, potatoes, bread or cassava.',
        'Protein: beans, groundnuts, eggs, fish, chicken, meat or soya.',
        'Vegetables: leafy greens such as rape, pumpkin leaves, chibwabwa, spinach.',
        'Fruit: mango, pawpaw, banana, orange, guava — whatever is in season.',
        'A little fat or oil for energy.',
      ]),
      h('Foods that help with common problems'),
      ul([
        'Anaemia (low blood): dark green leaves, liver, red meat, beans, and your prescribed iron supplement.',
        'Constipation: more water, vegetables, whole grains and fruit with the skin on.',
        'Nausea: dry food such as bread or crackers before getting up, small frequent meals, and ginger tea.',
        'Heartburn: smaller meals, avoid very spicy or fatty food, and do not lie down straight after eating.',
      ]),
      h('Avoid'),
      ul([
        'Alcohol — there is no known safe amount in pregnancy.',
        'Raw or undercooked meat, fish and eggs.',
        'Unpasteurised milk and soft cheeses made from it.',
        'Very salty packaged snacks, and sugary drinks.',
        'Excess caffeine (more than about two cups of tea or coffee a day).',
      ]),
      note('Wash vegetables and fruit in safe water, and keep raw meat away from food you eat uncooked.'),
      p(SEE_A_PROVIDER),
    ],
  },
  {
    slug: 'iron-and-folic-acid',
    title: 'Iron and folic acid in pregnancy',
    summary: 'Why these supplements are given, and how to take them so they work.',
    category: 'nutrition',
    tags: ['supplements', 'anaemia'],
    minutes: 3,
    blocks: [
      p('Antenatal clinics give iron and folic acid tablets to most pregnant women. Folic acid helps the baby\'s spine and brain develop in the first weeks. Iron helps prevent anaemia, which makes you tired and increases the risk of bleeding at delivery.'),
      h('Getting the most from your tablets'),
      ul([
        'Take them exactly as your provider prescribed — do not change the dose yourself.',
        'Take iron with fruit juice or a vitamin C-rich food; it absorbs better.',
        'Do not take iron with tea, coffee or milk — wait about an hour.',
        'If they make you constipated or nauseous, tell your provider rather than stopping.',
        'Keep them where children cannot reach them. Iron tablets are dangerous to a small child.',
      ]),
      note('Mama Care reminds you to take what was prescribed. It never suggests a medicine or a dose.'),
      p(SEE_A_PROVIDER),
    ],
  },
  {
    slug: 'malaria-in-pregnancy',
    title: 'Malaria prevention in pregnancy',
    summary: 'Sleeping under a treated net, preventive treatment, and when to get tested.',
    category: 'pregnancy',
    tags: ['malaria', 'prevention'],
    minutes: 4,
    blocks: [
      p('Malaria in pregnancy can cause anaemia, low birth weight and early delivery. Prevention is one of the most effective things you can do.'),
      h('Protect yourself'),
      ul([
        'Sleep under a long-lasting insecticide-treated net every night, and make sure it is tucked in with no holes.',
        'Take the preventive treatment your antenatal clinic gives you (IPTp), at the visits where it is offered.',
        'Cover arms and legs in the evening where possible.',
        'Remove standing water around the home where mosquitoes breed.',
        'Attend every antenatal visit so you receive the doses that are due.',
      ]),
      h('Get tested quickly if you have'),
      ul(['Fever.', 'Headache.', 'Chills or sweating.', 'Body aches and tiredness.', 'Vomiting.']),
      note('Fever in pregnancy needs same-day assessment. Tell the health worker you are pregnant and how far along you are.', 'warning'),
      p(SEE_A_PROVIDER),
    ],
  },
  {
    slug: 'staying-active',
    title: 'Exercise and activity in pregnancy',
    summary: 'What is safe, what to avoid, and when to stop and ask.',
    category: 'activity',
    tags: ['exercise', 'wellbeing'],
    minutes: 3,
    blocks: [
      p('Most women can stay active throughout pregnancy. Activity helps with back pain, sleep, mood, and stamina for labour.'),
      h('Usually safe'),
      ul(['Walking.', 'Gentle stretching and pregnancy exercises shown by your provider.', 'Household work at a comfortable pace.', 'Swimming, if you have safe access to clean water.', 'Continuing exercise you already did, at a lower intensity.']),
      h('Avoid'),
      ul([
        'Contact sports or anything with a high chance of falling.',
        'Lifting heavy loads, especially in later pregnancy.',
        'Exercise lying flat on your back after about 16 weeks.',
        'Exercising in very hot conditions or when you are dehydrated.',
        'Starting a hard new routine without asking your provider.',
      ]),
      note('Stop and contact your provider if you have bleeding, dizziness, chest pain, breathlessness at rest, calf pain or swelling, or reduced baby movements.', 'danger'),
      p(SEE_A_PROVIDER),
    ],
  },
  {
    slug: 'rest-and-sleep',
    title: 'Rest and sleep',
    summary: 'Sleeping position, dealing with heartburn and cramps, and why rest counts.',
    category: 'rest',
    tags: ['sleep', 'rest'],
    minutes: 3,
    blocks: [
      p('Tiredness is a real symptom of pregnancy, not a personal failing. Your body is doing a great deal of work.'),
      h('Sleeping on your side'),
      p('From around 16 weeks, sleeping on your side is recommended rather than flat on your back. If you wake on your back, simply turn onto your side. A pillow behind your back helps you stay there.'),
      h('For common night problems'),
      ul([
        'Heartburn: eat your last meal two to three hours before bed and prop yourself up with pillows.',
        'Leg cramps: stretch the calf gently, and ask your provider about your calcium and magnesium intake.',
        'Frequent urination: reduce drinks an hour before bed, but keep drinking during the day.',
        'Restless legs: a warm bath and gentle massage before sleep.',
      ]),
      p('Rest during the day when you can. In later pregnancy, a short afternoon rest makes a real difference.'),
      p(SEE_A_PROVIDER),
    ],
  },
  {
    slug: 'emotional-wellbeing',
    title: 'Emotional wellbeing in pregnancy and after birth',
    summary: 'Mood changes are common. Knowing the difference between common and concerning matters.',
    category: 'wellbeing',
    tags: ['mental health', 'wellbeing'],
    minutes: 5,
    blocks: [
      p('Pregnancy and the weeks after birth bring big hormonal changes, big life changes and often little sleep. Feeling tearful, anxious or overwhelmed at times is common.'),
      h('Things that help'),
      ul([
        'Tell someone you trust how you feel — a partner, a parent, a friend.',
        'Sleep when the baby sleeps, and accept help with chores.',
        'Keep eating regularly, even when you do not feel like it.',
        'Gentle daily activity, such as a short walk.',
        'Reduce pressure on yourself: you are learning, not performing.',
      ]),
      h('Ask for help promptly if'),
      ul([
        'You feel low, hopeless or unable to enjoy things most days for more than two weeks.',
        'You feel panicky, or cannot cope with daily tasks.',
        'You are not eating or sleeping.',
        'You feel unable to bond with your baby.',
        'You have thoughts of harming yourself or your baby.',
      ]),
      note('Thoughts of harming yourself or your baby need professional help today. Tell someone you trust now and contact your health facility. This is treatable and you are not alone.', 'danger'),
      p(SEE_A_PROVIDER),
    ],
  },
  {
    slug: 'birth-plan',
    title: 'Planning your birth',
    summary: 'The decisions worth making before labour starts, while you have time to think.',
    category: 'labour',
    week: 32,
    tags: ['birth plan', 'labour'],
    minutes: 4,
    blocks: [
      p('A birth plan is simply a list of your preferences and your practical arrangements. Discuss it with your provider at an antenatal visit — they can tell you what is possible where you will deliver.'),
      h('Practical arrangements'),
      ul([
        'Which facility you will go to, and a backup if it is full.',
        'How you will get there, at night as well as during the day, and what it will cost.',
        'Who you will leave your other children with.',
        'Who will go with you, and a second person to help at home.',
        'Money set aside for transport, and for anything the facility asks you to buy.',
        'Your bag, packed from about 36 weeks.',
      ]),
      h('Preferences worth writing down'),
      ul([
        'Who you want present during labour and delivery.',
        'Pain relief you would like, if available.',
        'How you want to be kept informed and involved in decisions.',
        'Whether you want the baby placed on your chest straight after birth.',
        'Who will make decisions for you if you are unable to.',
      ]),
      note('Plans change in labour, and that is normal. What matters is that you and your baby are safe — a provider may need to change the plan, and they should explain why.'),
      p(SEE_A_PROVIDER),
    ],
  },
  {
    slug: 'signs-labour-has-started',
    title: 'How to tell labour has started',
    summary: 'Contractions, the show, and your waters breaking — and when to leave for the facility.',
    category: 'labour',
    week: 37,
    tags: ['labour', 'when to go'],
    minutes: 4,
    blocks: [
      h('Contractions'),
      p('Practice contractions (Braxton Hicks) come irregularly, are usually mild, and ease when you rest or change position. Labour contractions become regular, stronger, closer together, and do not stop when you rest.'),
      ul(['Time them: how long each lasts, and how often they come.', 'In early labour they may be 10–15 minutes apart.', 'When they come about every 5 minutes and last about a minute, for an hour, go to the facility.', 'If this is not your first baby, go earlier — labour is often faster.']),
      h('The show'),
      p('A small amount of blood-stained mucus can be released as the cervix starts to open. This is common. Bleeding like a period, or more, is not — seek care immediately.'),
      h('Your waters breaking'),
      p('This may be a gush or a trickle of fluid you cannot control. Note the time, the colour and any smell, and go to the facility even if you have no contractions. Green or brown-stained fluid, or a foul smell, needs urgent attention.'),
      note('Go to the facility immediately if you have heavy bleeding, severe continuous pain, a fever, the baby moving less than usual, a fit, or if you are less than 37 weeks pregnant and having regular contractions.', 'danger'),
      p(SEE_A_PROVIDER),
    ],
  },
  {
    slug: 'what-to-pack',
    title: 'What to pack for the facility',
    summary: 'A short, practical list — pack it by 36 weeks and keep it by the door.',
    category: 'labour',
    tags: ['hospital bag', 'preparation'],
    minutes: 3,
    blocks: [
      h('For you'),
      ul([
        'Two or three comfortable dresses or a wrapper and tops.',
        'Underwear and several pairs of socks.',
        'Sanitary pads (bring more than you think you need).',
        'A cardigan or blanket.',
        'Toiletries, a towel and a comb.',
        'Slippers.',
      ]),
      h('For the baby'),
      ul(['Three or four cotton vests and nappies or cloth.', 'Two blankets and a hat.', 'A going-home outfit.', 'Baby soap and a soft cloth.']),
      h('Documents and money'),
      ul(['Your antenatal health card.', 'National ID or NRIC.', 'Insurance or exemption documents if you have them.', 'Transport money and some extra.', 'Phone and charger.']),
      note('Ask your facility if they provide any of these items — many government facilities supply basics, and knowing in advance avoids buying twice.'),
    ],
  },
  {
    slug: 'first-hours-after-birth',
    title: 'The first hours after birth',
    summary: 'Skin-to-skin contact, the first breastfeed, and what the health worker will do.',
    category: 'postnatal',
    tags: ['delivery', 'newborn', 'breastfeeding'],
    minutes: 4,
    blocks: [
      p('The first hour after birth matters a great deal for both of you.'),
      h('Skin-to-skin contact'),
      p('If you and your baby are well, the baby is usually dried and placed on your chest, covered with a warm dry cloth and a hat. This keeps the baby warm, steadies their breathing and heart rate, and helps them find the breast.'),
      h('The first breastfeed'),
      p('Most babies show feeding cues within the first hour — rooting, sucking their hands, moving towards the breast. Colostrum, the thick yellow first milk, comes in small amounts and is exactly what a newborn needs. It also helps the uterus contract, which reduces bleeding.'),
      h('What the health worker usually does'),
      ul([
        'Checks the baby\'s breathing, colour, tone and temperature, and records an Apgar score.',
        'Clamps and cuts the cord.',
        'Weighs and measures the baby.',
        'Gives vitamin K and eye ointment where these are routine.',
        'Gives BCG and the polio birth dose, or schedules them.',
        'Checks that the placenta is complete and monitors your bleeding and blood pressure.',
      ]),
      note('Bleeding after birth is monitored closely. If you soak a pad in an hour, feel faint, or have severe pain, tell a health worker immediately.', 'danger'),
      p(SEE_A_PROVIDER),
    ],
  },
  {
    slug: 'recovering-after-birth',
    title: 'Recovering after birth',
    summary: 'Bleeding, stitches, tiredness, and how to look after yourself in the first six weeks.',
    category: 'postnatal',
    tags: ['recovery', 'postnatal'],
    minutes: 5,
    blocks: [
      h('Bleeding (lochia)'),
      p('Bleeding after birth is normal. It is usually heavy for the first few days, then becomes brownish and lighter over two to six weeks. It may increase when you are more active, or when you breastfeed.'),
      note('Seek care now if you soak more than one pad in an hour, pass clots larger than a lemon, or the bleeding becomes bright red again after it had lightened.', 'danger'),
      h('Stitches and perineal care'),
      ul([
        'Keep the area clean and dry. Change pads regularly, front to back.',
        'Wash with clean water; do not use strong soaps or antiseptics unless advised.',
        'Sitting on a soft cushion helps in the first days.',
        'Tell your provider if the area becomes more painful, red, swollen, smelly or hot.',
      ]),
      h('After a caesarean section'),
      ul([
        'Keep the wound clean and dry and follow the instructions you were given.',
        'Avoid lifting anything heavier than your baby for the first weeks.',
        'Ask for help with stairs, carrying and household tasks.',
        'Report fever, increasing pain, redness, discharge or the wound opening.',
      ]),
      h('General recovery'),
      ul([
        'Rest when the baby rests. Sleep debt is real and slows recovery.',
        'Eat regular meals and keep drinking water, especially while breastfeeding.',
        'After-pains (cramps) are common when breastfeeding and usually settle.',
        'Take only medicine your provider has prescribed or approved.',
        'Attend your postnatal visit — usually within the first week, then at six weeks.',
      ]),
      p(SEE_A_PROVIDER),
    ],
  },
  {
    slug: 'postnatal-visits',
    title: 'Postnatal visits for you and your baby',
    summary: 'When to go back, what is checked, and why the first week matters most.',
    category: 'postnatal',
    tags: ['postnatal', 'appointments'],
    minutes: 3,
    blocks: [
      p('Most deaths of mothers and newborns happen in the first week after birth. Postnatal visits are how problems are found early.'),
      h('Recommended timing'),
      ol(['Within 24 hours of birth, if you delivered at home.', 'Between day 3 and day 7.', 'At 6 weeks.', 'At 6 months, with the baby\'s immunizations.']),
      h('What is checked for you'),
      ul(['Bleeding and how the uterus is shrinking back.', 'Blood pressure and temperature.', 'Any stitches or caesarean wound.', 'Breasts and breastfeeding.', 'How you are feeling emotionally.', 'Family planning.']),
      h('What is checked for the baby'),
      ul(['Weight and growth.', 'Feeding and how many wet nappies.', 'Jaundice.', 'The cord stump.', 'Development and responsiveness.', 'Immunizations due.']),
      note('If either of you is unwell between visits, do not wait for the next appointment.'),
      p(SEE_A_PROVIDER),
    ],
  },
  {
    slug: 'breastfeeding-basics',
    title: 'Breastfeeding basics',
    summary: 'How often to feed, how to tell the baby is getting enough, and what is normal.',
    category: 'breastfeeding',
    tags: ['breastfeeding', 'newborn'],
    minutes: 5,
    blocks: [
      h('In the first days'),
      p('Colostrum comes in small amounts — a teaspoon or less per feed — and that is enough for a newborn\'s tiny stomach. Feed on demand: whenever the baby shows cues, day and night, usually 8 to 12 times in 24 hours.'),
      h('Feeding cues'),
      ul(['Rooting or turning the head.', 'Sucking hands or fingers.', 'Smacking lips.', 'Stirring or waking. Crying is a late cue — try to feed before it.']),
      h('How to know the baby is getting enough'),
      ul([
        'Six or more heavy wet nappies in 24 hours after day four.',
        'Stools changing from black sticky meconium to yellow and seedy by day four to five.',
        'The baby is settled and relaxed after most feeds, with hands open.',
        'You can hear swallowing.',
        'Weight: babies normally lose a little weight in the first days and regain birth weight by about two weeks.',
      ]),
      h('What is normal'),
      ul([
        'Cluster feeding in the evening — many short feeds close together.',
        'Sore nipples for the first few days (cracked, bleeding or very painful nipples mean the attachment needs help).',
        'Breasts feeling full and firm, then softer after feeds.',
        'Growth spurts around 3 weeks, 6 weeks and 3 months, when the baby wants to feed constantly.',
      ]),
      note('Do not give water, gripe water, porridge or formula unless a health worker advises it. Extra drinks reduce breastmilk supply and increase the risk of infection.', 'warning'),
      p(SEE_A_PROVIDER),
    ],
  },
  {
    slug: 'breastfeeding-attachment',
    title: 'Position and attachment',
    summary: 'A good latch prevents most breastfeeding pain. Here is how to check it.',
    category: 'breastfeeding',
    tags: ['breastfeeding', 'latch'],
    minutes: 4,
    blocks: [
      h('Position'),
      ul([
        'Get comfortable and supported first — pillows behind your back and under your arm.',
        'Bring the baby to the breast, not the breast to the baby.',
        'Baby\'s head, shoulders and hips in a straight line, facing you, tummy to tummy.',
        'Baby\'s nose level with your nipple, so they tilt the head back to latch.',
      ]),
      h('Attachment'),
      ol([
        'Tickle the upper lip with the nipple and wait for a wide open mouth, like a yawn.',
        'Move the baby on quickly, chin first, so the nipple points to the roof of the mouth.',
        'More of the dark area (areola) should be in the baby\'s mouth below the nipple than above.',
        'Lips flanged outward, chin touching the breast, nose free.',
      ]),
      h('Signs the latch is good'),
      ul(['Feeding is comfortable — a pulling sensation, not pain.', 'Cheeks are rounded, not sucked in.', 'You can hear or see swallowing.', 'The nipple looks round, not creased or pinched, after the feed.']),
      h('If it hurts'),
      p('Break the suction gently with a clean finger in the corner of the mouth, then start again. Persistent pain usually means the latch needs adjusting — ask for hands-on help from a health worker or a trained counsellor rather than putting up with it.'),
      p(SEE_A_PROVIDER),
    ],
  },
  {
    slug: 'breastfeeding-challenges',
    title: 'Common breastfeeding challenges',
    summary: 'Engorgement, blocked ducts, mastitis, cracked nipples and low supply.',
    category: 'breastfeeding',
    tags: ['breastfeeding', 'problems'],
    minutes: 5,
    blocks: [
      h('Engorgement (breasts hard, hot and painful)'),
      ul(['Feed more often, not less.', 'Warm compress before a feed, cold compress after.', 'Gentle hand expression to soften the area before the baby latches.', 'Supportive, non-tight bra.']),
      h('Blocked duct'),
      p('A tender lump, sometimes with a white spot on the nipple. Keep feeding from that side first, use warmth before feeds, and gently massage towards the nipple while feeding.'),
      h('Mastitis'),
      ul([
        'A red, hot, painful wedge-shaped area on the breast.',
        'Fever, chills and feeling like you have flu.',
        'Keep breastfeeding or expressing — it is safe for the baby and it helps you recover.',
        'Rest, fluids, and see a health worker the same day: you may need treatment.',
      ]),
      note('A fever with a painful red area on the breast needs same-day assessment. Do not wait it out.', 'warning'),
      h('Cracked or sore nipples'),
      ul(['Check and improve the attachment — this is the usual cause.', 'Express a little milk and let it dry on the nipple after feeds.', 'Keep nipples dry; change damp breast pads often.', 'Do not use soap on the nipples.']),
      h('"My milk is not enough"'),
      p('Milk supply responds to demand. Feeding more often, emptying the breast well, resting, drinking to thirst and eating regularly all help. A baby who is gaining weight and having six or more wet nappies a day is getting enough, even if they seem to want to feed constantly.'),
      note('Ask your provider or a breastfeeding counsellor to weigh the baby and check before giving anything else.', 'info'),
      p(SEE_A_PROVIDER),
    ],
  },
  {
    slug: 'newborn-care-basics',
    title: 'Looking after a newborn',
    summary: 'Warmth, feeding, sleep safety, hygiene and what is normal in the first weeks.',
    category: 'newborn',
    tags: ['newborn', 'care'],
    minutes: 5,
    blocks: [
      h('Keeping the baby warm'),
      ul(['Dress the baby in one more layer than you are wearing.', 'A hat in cool weather.', 'Skin-to-skin contact is the best way to warm a cool baby.', 'Feel the chest or back to check temperature, not the hands or feet.']),
      h('Sleep safety'),
      ul(['Always on the back, for every sleep.', 'A firm flat surface with no pillows, loose bedding or soft toys.', 'In your room, close to your bed, for the first six months.', 'Never on a sofa or armchair with an adult.']),
      h('Hygiene'),
      ul(['Wash your hands before handling the baby, and ask visitors to as well.', 'Keep the cord stump clean and dry — no applying anything unless advised.', 'Bathe the baby when the cord has healed, or sponge before then.', 'Nappies changed often, wiped front to back for girls.']),
      h('Normal newborn things'),
      ul([
        'Mild yellowing of the skin after day two (physiological jaundice) — but jaundice in the first 24 hours needs assessment.',
        'Crossed eyes occasionally in the first weeks.',
        'Sneezing, hiccups and noisy breathing.',
        'Peeling skin, small white spots on the face, and a rash from nappies.',
        'Losing a little weight in the first few days.',
      ]),
      note('A newborn with fever, poor feeding, fast or difficult breathing, unusual sleepiness, or convulsions must be seen urgently — the same day.', 'danger'),
      p(SEE_A_PROVIDER),
    ],
  },
  {
    slug: 'starting-complementary-foods',
    title: 'Starting solid food at six months',
    summary: 'When, what, how much, and how to keep food safe.',
    category: 'newborn',
    tags: ['feeding', 'nutrition', 'weaning'],
    minutes: 4,
    blocks: [
      p('From about six months, breastmilk alone no longer covers everything a growing baby needs. Complementary food is added while breastfeeding continues.'),
      h('Signs the baby is ready'),
      ul(['Sits up with little support and holds the head steady.', 'Shows interest in food and reaches for it.', 'The tongue-thrust reflex has faded, so food stays in the mouth.']),
      h('How to start'),
      ol([
        'Two to three spoons once a day, then build up.',
        'Mashed or pureed family food — soft enough to eat without chewing.',
        'Gradually thicken and add small soft pieces as the baby manages.',
        'Three meals and one or two snacks a day by 9–12 months.',
        'Keep breastfeeding for as long as you and the baby wish.',
      ]),
      h('Good first foods'),
      ul([
        'Enriched porridge: add oil, groundnut powder, mashed egg or beans.',
        'Mashed vegetables and fruit: pumpkin, sweet potato, carrot, banana, pawpaw, avocado.',
        'Protein: mashed beans, egg, fish with bones removed, minced meat.',
        'Foods rich in vitamin A and iron are especially important.',
      ]),
      h('Avoid'),
      ul(['Honey before 12 months.', 'Whole nuts, grapes and hard raw vegetables — choking risk.', 'Added salt and sugar.', 'Sweet drinks and juice.', 'Tea or coffee, which block iron absorption.']),
      note('Wash hands before preparing food, use clean utensils, and keep cooked food covered. Diarrhoea is often caused by unsafe food or water.'),
      p(SEE_A_PROVIDER),
    ],
  },
  {
    slug: 'immunization-why-it-matters',
    title: 'Why immunization matters',
    summary: 'How vaccines protect your baby, what to expect afterwards, and how to keep the record complete.',
    category: 'immunization',
    tags: ['immunization', 'vaccines'],
    minutes: 4,
    blocks: [
      p('Vaccines train a baby\'s immune system to recognise an illness before they meet it. Most of the diseases they prevent — polio, measles, whooping cough, tetanus, pneumonia, severe diarrhoea — have no treatment once they start, and can kill or permanently disable a small baby.'),
      h('What to expect afterwards'),
      ul([
        'Soreness, redness or a small lump where the injection was given.',
        'Mild fever for a day or two.',
        'Being unsettled or sleepier than usual.',
        'A reduced appetite for a short while.',
      ]),
      h('Get the baby seen if'),
      ul([
        'Fever of 38 °C or more that does not settle, or any fever under 3 months.',
        'Continuous inconsolable crying for more than three hours.',
        'A convulsion, or the baby becoming floppy or unresponsive.',
        'Difficulty breathing or swelling of the face — seek care immediately.',
      ]),
      h('Keeping the record complete'),
      ul([
        'Bring the child health card to every visit.',
        'Complete the full series — a single dose often does not protect.',
        'If you miss a date, go as soon as you can. The series is usually continued, not restarted.',
        'Keep the card safe: it may be needed for school and travel.',
      ]),
      note('Mama Care shows the national schedule and reminds you of dates. Only a health worker decides what your baby receives and when.'),
      p(SEE_A_PROVIDER),
    ],
  },
  {
    slug: 'danger-signs-in-pregnancy',
    title: 'Danger signs in pregnancy',
    summary: 'The symptoms that mean go now, and the ones that mean get seen today.',
    category: 'pregnancy',
    tags: ['emergency', 'danger signs'],
    minutes: 4,
    blocks: [
      note('This page does not diagnose. It tells you when to get help, and how quickly.', 'danger'),
      h('Go to a facility now'),
      ul([
        'Heavy bleeding, or any bleeding with pain.',
        'Severe or continuous abdominal pain.',
        'A fit or convulsion.',
        'Fainting or loss of consciousness.',
        'Difficulty breathing or chest pain.',
        'Severe headache with blurred vision or swelling of the face and hands.',
        'A gush of fluid before labour starts, especially if green, brown or smelly.',
        'Reduced or absent baby movements after 24 weeks.',
        'Regular painful contractions before 37 weeks.',
      ]),
      h('Get seen today'),
      ul([
        'Fever of 38 °C or more.',
        'Vomiting that stops you keeping fluids down.',
        'Pain or burning when passing urine, or cloudy urine.',
        'Itchy, sore or foul-smelling vaginal discharge.',
        'A fall or injury to the belly.',
        'Severe swelling that comes on quickly.',
      ]),
      h('Before you go'),
      ul([
        'Tell someone where you are going and go with them if you can.',
        'Take your antenatal health card.',
        'Note the time symptoms started and anything that makes them better or worse.',
        'If you cannot reach a facility, call your provider or the emergency number on the Emergency screen.',
      ]),
      p(SEE_A_PROVIDER),
    ],
  },
  {
    slug: 'danger-signs-in-newborns',
    title: 'Danger signs in newborns',
    summary: 'A newborn can become seriously ill very quickly. Learn these signs.',
    category: 'newborn',
    tags: ['emergency', 'newborn', 'danger signs'],
    minutes: 3,
    blocks: [
      note('Newborns deteriorate fast and show few signs. When in doubt, get the baby seen.', 'danger'),
      h('Go to a facility immediately'),
      ul([
        'Fast breathing, grunting, flaring nostrils, or the chest pulling in between the ribs.',
        'Fever of 38 °C or more, or a temperature below 36 °C.',
        'Convulsions, jerking, or abnormal movements.',
        'Too sleepy to wake, or floppy.',
        'Not feeding at all, or refusing several feeds in a row.',
        'Blue or grey lips, tongue or face.',
        'A bulging or very sunken soft spot on the head.',
      ]),
      h('Get the baby seen today'),
      ul([
        'Yellow palms or soles, or jaundice appearing in the first 24 hours.',
        'Fewer wet nappies than usual.',
        'A red, swollen, smelly or discharging cord stump.',
        'Pus or discharge from the eyes.',
        'Diarrhoea or vomiting.',
        'A rash with blisters or peeling skin.',
      ]),
      p(SEE_A_PROVIDER),
    ],
  },
  {
    slug: 'family-planning-after-birth',
    title: 'Family planning after birth',
    summary: 'Why spacing pregnancies matters, and when to discuss your options.',
    category: 'postnatal',
    tags: ['family planning', 'postnatal'],
    minutes: 4,
    blocks: [
      p('You can become pregnant again before your first period returns after birth, so it is worth talking to a provider before you leave the facility or at your six-week visit.'),
      h('Why spacing matters'),
      ul([
        'Waiting at least two years before the next pregnancy lowers the risk for both mother and baby.',
        'Your body needs time to recover iron and nutrient stores.',
        'Older babies are easier to care for alongside a newborn.',
      ]),
      h('Talking to a provider'),
      p('Methods differ in how they are used, how long they last, and whether they affect breastfeeding. A provider can explain what is available locally and what suits your health, your plans and your relationship. Some methods can be started immediately after birth; others are usually started at six weeks.'),
      note('Mama Care does not recommend a method. Choose with a qualified provider who knows your health history.'),
      p(SEE_A_PROVIDER),
    ],
  },
  {
    slug: 'hiv-and-pregnancy',
    title: 'HIV testing and treatment in pregnancy',
    summary: 'With treatment, mothers living with HIV can have babies who are HIV-negative.',
    category: 'antenatal-care',
    tags: ['hiv', 'pmtct', 'antenatal'],
    minutes: 4,
    blocks: [
      p('Every antenatal clinic offers an HIV test. Testing early means treatment can start early, and treatment works: mothers living with HIV who take their medicine as prescribed can have babies who do not have HIV.'),
      h('What is offered'),
      ul([
        'An HIV test at your first antenatal visit, and again later in pregnancy or while breastfeeding where this is routine.',
        'Antiretroviral treatment (ART) for mothers who test positive — started as soon as possible and continued for life.',
        'Preventive medicine for the baby after birth.',
        'Advice on feeding: with treatment and support, breastfeeding is recommended, and mixed feeding should be discussed with your provider.',
        'Testing for the baby at the ages the programme recommends.',
      ]),
      h('What helps'),
      ul([
        'Take ART every day, at the same time.',
        'Keep every clinic appointment and collect medicine before it runs out.',
        'Tell your provider about any side effects rather than stopping.',
        'Ask about support groups — many facilities run them.',
      ]),
      note('Your HIV status is confidential. If you are worried about how a result will be handled, say so to the health worker — there are services designed for exactly this.'),
      p(SEE_A_PROVIDER),
    ],
  },
  {
    slug: 'hiv-exposed-infants',
    title: 'Caring for an HIV-exposed infant',
    summary: 'Follow-up testing, medicine for the baby, and feeding guidance.',
    category: 'postnatal',
    tags: ['hiv', 'infant', 'testing'],
    minutes: 3,
    blocks: [
      p('A baby born to a mother living with HIV is called an HIV-exposed infant. With the right follow-up, most of these babies are HIV-negative.'),
      h('What usually happens'),
      ul([
        'The baby receives preventive medicine, started as soon as possible after birth.',
        'Tests are done at the ages the national programme recommends, and again after breastfeeding ends.',
        'The mother continues her own ART — this protects her health and reduces transmission.',
        'Growth, feeding and development are checked at every visit.',
      ]),
      h('Feeding'),
      p('National guidance supports breastfeeding with maternal treatment. Exclusive breastfeeding for six months — no water, no other food or drink — is usually recommended, with complementary foods added from six months while breastfeeding continues. Ask your provider what applies to you, and tell them if your situation makes that difficult.'),
      note('Never stop your own treatment or the baby\'s preventive medicine without talking to your provider first.', 'warning'),
      p(SEE_A_PROVIDER),
    ],
  },
  {
    slug: 'caring-for-yourself-as-a-supporter',
    title: 'For partners and family: how to help',
    summary: 'Practical support that actually makes a difference, for the person on a shared account.',
    category: 'wellbeing',
    tags: ['supporter', 'family'],
    minutes: 3,
    blocks: [
      p('A mother who is supported has an easier pregnancy and an easier recovery. Most support is ordinary and practical.'),
      h('During pregnancy'),
      ul([
        'Go to antenatal visits when you can, and listen.',
        'Take over heavy lifting, long standing and late-night errands.',
        'Help her keep appointments and take prescribed supplements.',
        'Learn the danger signs too — you may be the one who notices first.',
        'Plan transport to the facility and agree who stays with other children.',
      ]),
      h('After birth'),
      ul([
        'Handle night-time nappy changes and settling so she can sleep in stretches.',
        'Bring the baby to her for feeds, and keep visitors managed.',
        'Cook, wash and shop without being asked.',
        'Watch for signs of low mood, and encourage her to speak to a provider.',
        'Never smoke near the baby or in the house.',
      ]),
      note('A supporter account only shows what the mother chooses to share. She controls it, and can change or remove access at any time.'),
    ],
  },
];

/** Built-in articles as domain records (stable ids derived from the slug). */
export const BUILTIN_ARTICLES: Article[] = ARTICLE_SEEDS.map((seed, index) => ({
  id: `builtin-${seed.slug}`,
  slug: seed.slug,
  title: seed.title,
  summary: seed.summary,
  category: seed.category,
  weekNumber: seed.week ?? null,
  audience: 'public',
  language: 'en',
  blocks: seed.blocks,
  imageUrl: null,
  imagePublicId: null,
  tags: seed.tags,
  status: 'published',
  authorName: 'Mama Care',
  reviewedBy: null,
  reviewedAt: null,
  readMinutes: seed.minutes,
  builtin: true,
  createdAt: new Date(Date.UTC(2025, 0, 1 + index)).toISOString(),
  updatedAt: null,
}));

export const builtinArticle = (slug: string): Article | undefined =>
  BUILTIN_ARTICLES.find((article) => article.slug === slug);
