/**
 * Starter facility directory (Zambia).
 *
 * Seeded on first run so the directory is useful immediately, in both device mode
 * and a fresh Firebase project. Two honesty rules shape this data:
 *
 *  1. **Phone numbers are left empty on purpose.** An invented or out-of-date
 *     number in an emergency is worse than no number. Administrators add and
 *     verify contact details (`verified` / `verifiedAt`) before a facility is
 *     shown as verified in the app.
 *  2. **Coordinates are approximate** and are used only to sort facilities by
 *     distance and to centre a map link — never for navigation.
 *
 * Every entry starts `verified: false`. The public screens say when a listing has
 * not been verified yet.
 */

import type { Facility } from '@/types/domain';

export const FACILITY_DATA_NOTE =
  'Facility details in this directory are maintained by Mama Care administrators and should be confirmed by phone or in person before you travel. Entries marked "Not yet verified" have not been checked recently.';

interface FacilitySeed {
  name: string;
  type: Facility['type'];
  city: string;
  province: string;
  address: string;
  lat: number;
  lng: number;
  services: string[];
  maternalServices: string[];
  openingHours: string;
  hasMaternity: boolean;
  has24HourEmergency: boolean;
}

const LUSAKA = [-15.3875, 28.3228] as const;

const SEEDS: FacilitySeed[] = [
  {
    name: 'University Teaching Hospital (UTH)',
    type: 'government-hospital',
    city: 'Lusaka',
    province: 'Lusaka',
    address: 'Nasser Road, Lusaka',
    lat: -15.3985,
    lng: 28.3228,
    services: ['Emergency', 'Maternity', 'Surgery', 'Paediatrics', 'Intensive care', 'Blood transfusion', 'Laboratory', 'Ultrasound'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Caesarean section', 'Obstetric high-dependency care', 'Newborn care unit', 'Family planning', 'Cervical cancer screening'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: true,
  },
  {
    name: 'Levy Mwanawasa University Teaching Hospital',
    type: 'government-hospital',
    city: 'Lusaka',
    province: 'Lusaka',
    address: 'Great East Road, Chelstone, Lusaka',
    lat: -15.3922,
    lng: 28.3967,
    services: ['Emergency', 'Maternity', 'Surgery', 'Paediatrics', 'Laboratory', 'Imaging'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Caesarean section', 'Newborn care', 'Family planning'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: true,
  },
  {
    name: 'Chainama Mission Hospital',
    type: 'government-hospital',
    city: 'Lusaka',
    province: 'Lusaka',
    address: 'Great East Road, Chainama, Lusaka',
    lat: -15.3778,
    lng: 28.3841,
    services: ['Emergency', 'Maternity', 'Surgery', 'Paediatrics', 'Laboratory'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Newborn care', 'Family planning'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: true,
  },
  {
    name: 'Chilenje Level One Hospital',
    type: 'government-hospital',
    city: 'Lusaka',
    province: 'Lusaka',
    address: 'Chilenje, Lusaka',
    lat: -15.4333,
    lng: 28.2667,
    services: ['Emergency', 'Maternity', 'Outpatient', 'Laboratory'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Postnatal clinic', 'Family planning', 'Child welfare clinic'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: true,
  },
  {
    name: 'Mtendere Mission Hospital',
    type: 'government-hospital',
    city: 'Lusaka',
    province: 'Lusaka',
    address: 'Mtendere, Chongwe Road, Lusaka',
    lat: -15.4167,
    lng: 28.4833,
    services: ['Emergency', 'Maternity', 'Surgery', 'Outpatient'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Postnatal clinic', 'Family planning'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: true,
  },
  {
    name: 'Coptic Hospital',
    type: 'private-hospital',
    city: 'Lusaka',
    province: 'Lusaka',
    address: 'Church Road, Roma, Lusaka',
    lat: -15.4067,
    lng: 28.3222,
    services: ['Emergency', 'Maternity', 'Surgery', 'Paediatrics', 'Laboratory'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Caesarean section', 'Newborn care', 'Family planning'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: true,
  },
  {
    name: 'Kabwata Clinic',
    type: 'clinic',
    city: 'Lusaka',
    province: 'Lusaka',
    address: 'Kabwata, Lusaka',
    lat: -15.4189,
    lng: 28.3061,
    services: ['Outpatient', 'Maternal and child health', 'Laboratory'],
    maternalServices: ['Antenatal clinic', 'Postnatal clinic', 'Child welfare clinic', 'Immunization', 'Family planning'],
    openingHours: 'Monday–Friday 07:30–17:00, Saturday 08:00–13:00',
    hasMaternity: true,
    has24HourEmergency: false,
  },
  {
    name: 'Kalingalinga Clinic',
    type: 'clinic',
    city: 'Lusaka',
    province: 'Lusaka',
    address: 'Kalingalinga, Lusaka',
    lat: -15.3833,
    lng: 28.3167,
    services: ['Outpatient', 'Maternal and child health', 'Immunization'],
    maternalServices: ['Antenatal clinic', 'Child welfare clinic', 'Immunization', 'Family planning', 'PMTCT'],
    openingHours: 'Monday–Friday 07:30–17:00',
    hasMaternity: false,
    has24HourEmergency: false,
  },
  {
    name: 'Garden Health Centre',
    type: 'health-post',
    city: 'Lusaka',
    province: 'Lusaka',
    address: 'Garden Compound, Lusaka',
    lat: -15.4,
    lng: 28.3333,
    services: ['Primary care', 'Maternal and child health'],
    maternalServices: ['Antenatal clinic', 'Immunization', 'Family planning', 'Health education'],
    openingHours: 'Monday–Friday 08:00–16:00',
    hasMaternity: false,
    has24HourEmergency: false,
  },
  {
    name: 'Chawama Health Centre',
    type: 'health-post',
    city: 'Lusaka',
    province: 'Lusaka',
    address: 'Chawama, Lusaka',
    lat: -15.4444,
    lng: 28.3111,
    services: ['Primary care', 'Maternal and child health', 'Outreach'],
    maternalServices: ['Antenatal clinic', 'Immunization', 'Family planning', 'Home visits'],
    openingHours: 'Monday–Friday 08:00–16:00',
    hasMaternity: false,
    has24HourEmergency: false,
  },
  {
    name: 'Livingstone University Teaching Hospital',
    type: 'government-hospital',
    city: 'Livingstone',
    province: 'Southern',
    address: 'Livingstone, Southern Province',
    lat: -17.8419,
    lng: 25.8544,
    services: ['Emergency', 'Maternity', 'Surgery', 'Paediatrics', 'Laboratory'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Caesarean section', 'Newborn care', 'Family planning'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: true,
  },
  {
    name: 'Monze Mission Hospital',
    type: 'government-hospital',
    city: 'Monze',
    province: 'Southern',
    address: 'Monze, Southern Province',
    lat: -16.2833,
    lng: 27.4833,
    services: ['Emergency', 'Maternity', 'Surgery', 'Outpatient'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Postnatal clinic', 'Family planning'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: true,
  },
  {
    name: 'Choma General Hospital',
    type: 'government-hospital',
    city: 'Choma',
    province: 'Southern',
    address: 'Choma, Southern Province',
    lat: -16.8,
    lng: 26.9833,
    services: ['Emergency', 'Maternity', 'Outpatient', 'Laboratory'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Child welfare clinic', 'Family planning'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: true,
  },
  {
    name: 'Ndola Central Hospital',
    type: 'government-hospital',
    city: 'Ndola',
    province: 'Copperbelt',
    address: 'Ndola, Copperbelt Province',
    lat: -12.9587,
    lng: 28.6366,
    services: ['Emergency', 'Maternity', 'Surgery', 'Paediatrics', 'Intensive care', 'Laboratory'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Caesarean section', 'Newborn care unit', 'Family planning'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: true,
  },
  {
    name: 'Kitwe Central Hospital',
    type: 'government-hospital',
    city: 'Kitwe',
    province: 'Copperbelt',
    address: 'Kitwe, Copperbelt Province',
    lat: -12.8028,
    lng: 28.2111,
    services: ['Emergency', 'Maternity', 'Surgery', 'Paediatrics', 'Laboratory'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Caesarean section', 'Family planning'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: true,
  },
  {
    name: 'Konkola Mine Hospital',
    type: 'private-hospital',
    city: 'Chingola',
    province: 'Copperbelt',
    address: 'Chingola, Copperbelt Province',
    lat: -12.5292,
    lng: 27.8522,
    services: ['Emergency', 'Maternity', 'Surgery', 'Occupational health'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Family planning'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: true,
  },
  {
    name: 'Mufulira Mine Hospital',
    type: 'private-hospital',
    city: 'Mufulira',
    province: 'Copperbelt',
    address: 'Mufulira, Copperbelt Province',
    lat: -12.55,
    lng: 28.25,
    services: ['Emergency', 'Maternity', 'Outpatient'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Family planning'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: true,
  },
  {
    name: 'Kabwe General Hospital',
    type: 'government-hospital',
    city: 'Kabwe',
    province: 'Central',
    address: 'Kabwe, Central Province',
    lat: -14.4469,
    lng: 28.4464,
    services: ['Emergency', 'Maternity', 'Surgery', 'Paediatrics', 'Laboratory'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Caesarean section', 'Family planning'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: true,
  },
  {
    name: 'Chipata General Hospital',
    type: 'government-hospital',
    city: 'Chipata',
    province: 'Eastern',
    address: 'Chipata, Eastern Province',
    lat: -13.6333,
    lng: 32.65,
    services: ['Emergency', 'Maternity', 'Surgery', 'Outpatient'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Postnatal clinic', 'Family planning'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: true,
  },
  {
    name: 'Petauke District Hospital',
    type: 'government-hospital',
    city: 'Petauke',
    province: 'Eastern',
    address: 'Petauke, Eastern Province',
    lat: -14.25,
    lng: 31.3167,
    services: ['Emergency', 'Maternity', 'Outpatient'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Immunization', 'Family planning'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: false,
  },
  {
    name: 'Kasama General Hospital',
    type: 'government-hospital',
    city: 'Kasama',
    province: 'Northern',
    address: 'Kasama, Northern Province',
    lat: -10.2167,
    lng: 31.1833,
    services: ['Emergency', 'Maternity', 'Surgery', 'Laboratory'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Caesarean section', 'Family planning'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: true,
  },
  {
    name: 'Mbala District Hospital',
    type: 'government-hospital',
    city: 'Mbala',
    province: 'Northern',
    address: 'Mbala, Northern Province',
    lat: -8.8333,
    lng: 31.3667,
    services: ['Emergency', 'Maternity', 'Outpatient'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Immunization'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: false,
  },
  {
    name: 'Mansa General Hospital',
    type: 'government-hospital',
    city: 'Mansa',
    province: 'Luapula',
    address: 'Mansa, Luapula Province',
    lat: -11.2,
    lng: 28.8833,
    services: ['Emergency', 'Maternity', 'Surgery', 'Outpatient'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Family planning'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: true,
  },
  {
    name: 'Nchelenge District Hospital',
    type: 'government-hospital',
    city: 'Nchelenge',
    province: 'Luapula',
    address: 'Nchelenge, Luapula Province',
    lat: -9.35,
    lng: 28.7333,
    services: ['Emergency', 'Maternity', 'Outpatient'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Immunization'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: false,
  },
  {
    name: 'Solwezi General Hospital',
    type: 'government-hospital',
    city: 'Solwezi',
    province: 'North-Western',
    address: 'Solwezi, North-Western Province',
    lat: -12.1833,
    lng: 26.4,
    services: ['Emergency', 'Maternity', 'Surgery', 'Laboratory'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Caesarean section', 'Family planning'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: true,
  },
  {
    name: 'Mongu Central Hospital',
    type: 'government-hospital',
    city: 'Mongu',
    province: 'Western',
    address: 'Mongu, Western Province',
    lat: -15.2833,
    lng: 23.1333,
    services: ['Emergency', 'Maternity', 'Surgery', 'Outpatient'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Postnatal clinic', 'Family planning'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: true,
  },
  {
    name: 'Senanga District Hospital',
    type: 'government-hospital',
    city: 'Senanga',
    province: 'Western',
    address: 'Senanga, Western Province',
    lat: -16.1167,
    lng: 23.2667,
    services: ['Emergency', 'Maternity', 'Outpatient'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Immunization'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: false,
  },
  {
    name: 'Kalabo District Hospital',
    type: 'government-hospital',
    city: 'Kalabo',
    province: 'Western',
    address: 'Kalabo, Western Province',
    lat: -14.9833,
    lng: 22.6667,
    services: ['Emergency', 'Maternity', 'Outpatient'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Immunization'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: false,
  },
  {
    name: 'Kasempa District Hospital',
    type: 'government-hospital',
    city: 'Kasempa',
    province: 'North-Western',
    address: 'Kasempa, North-Western Province',
    lat: -13.4583,
    lng: 25.8333,
    services: ['Emergency', 'Maternity', 'Outpatient'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Child welfare clinic'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: false,
  },
  {
    name: 'Sesheke District Hospital',
    type: 'government-hospital',
    city: 'Sesheke',
    province: 'Western',
    address: 'Sesheke, Western Province',
    lat: -17.4833,
    lng: 24.3,
    services: ['Emergency', 'Maternity', 'Outpatient'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Immunization'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: false,
  },
  {
    name: 'Chinsali District Hospital',
    type: 'government-hospital',
    city: 'Chinsali',
    province: 'Muchinga',
    address: 'Chinsali, Muchinga Province',
    lat: -10.55,
    lng: 32.0833,
    services: ['Emergency', 'Maternity', 'Outpatient'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Family planning'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: false,
  },
  {
    name: 'Mpika District Hospital',
    type: 'government-hospital',
    city: 'Mpika',
    province: 'Muchinga',
    address: 'Mpika, Muchinga Province',
    lat: -11.8333,
    lng: 31.45,
    services: ['Emergency', 'Maternity', 'Outpatient'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Immunization'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: false,
  },
  {
    name: 'Kafue District Hospital',
    type: 'government-hospital',
    city: 'Kafue',
    province: 'Lusaka',
    address: 'Kafue, Lusaka Province',
    lat: -15.7667,
    lng: 28.1833,
    services: ['Emergency', 'Maternity', 'Outpatient', 'Laboratory'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Postnatal clinic', 'Family planning'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: false,
  },
  {
    name: 'Chongwe District Hospital',
    type: 'government-hospital',
    city: 'Chongwe',
    province: 'Lusaka',
    address: 'Chongwe, Lusaka Province',
    lat: -15.3333,
    lng: 28.6667,
    services: ['Emergency', 'Maternity', 'Outpatient'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Immunization'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: false,
  },
  {
    name: 'Mazabuka District Hospital',
    type: 'government-hospital',
    city: 'Mazabuka',
    province: 'Southern',
    address: 'Mazabuka, Southern Province',
    lat: -15.85,
    lng: 27.75,
    services: ['Emergency', 'Maternity', 'Outpatient'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Child welfare clinic'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: false,
  },
  {
    name: 'Kapiri Mposhi District Hospital',
    type: 'government-hospital',
    city: 'Kapiri Mposhi',
    province: 'Central',
    address: 'Kapiri Mposhi, Central Province',
    lat: -13.9667,
    lng: 28.6833,
    services: ['Emergency', 'Maternity', 'Outpatient'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Immunization'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: false,
  },
  {
    name: 'Lundazi District Hospital',
    type: 'government-hospital',
    city: 'Lundazi',
    province: 'Eastern',
    address: 'Lundazi, Eastern Province',
    lat: -12.2833,
    lng: 33.1833,
    services: ['Emergency', 'Maternity', 'Outpatient'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Immunization'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: false,
  },
  {
    name: 'Mumbwa District Hospital',
    type: 'government-hospital',
    city: 'Mumbwa',
    province: 'Central',
    address: 'Mumbwa, Central Province',
    lat: -14.9833,
    lng: 27.0667,
    services: ['Emergency', 'Maternity', 'Outpatient'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Family planning'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: false,
  },
  {
    name: 'Samfya District Hospital',
    type: 'government-hospital',
    city: 'Samfya',
    province: 'Luapula',
    address: 'Samfya, Luapula Province',
    lat: -11.3667,
    lng: 29.55,
    services: ['Emergency', 'Maternity', 'Outpatient'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Immunization'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: false,
  },
  {
    name: 'Nakonde District Hospital',
    type: 'government-hospital',
    city: 'Nakonde',
    province: 'Muchinga',
    address: 'Nakonde, Muchinga Province',
    lat: -9.3333,
    lng: 32.75,
    services: ['Emergency', 'Maternity', 'Outpatient'],
    maternalServices: ['Antenatal clinic', 'Delivery suite', 'Immunization'],
    openingHours: 'Open 24 hours, every day',
    hasMaternity: true,
    has24HourEmergency: false,
  },
];

export const PROVINCES = [
  'Central',
  'Copperbelt',
  'Eastern',
  'Luapula',
  'Lusaka',
  'Muchinga',
  'North-Western',
  'Northern',
  'Southern',
  'Western',
];

/** Approximate centre of each province, used for distance sorting. */
export const PROVINCE_CENTRES: Record<string, [number, number]> = {
  Central: [-14.4469, 28.4464],
  Copperbelt: [-12.9587, 28.6366],
  Eastern: [-13.6333, 32.65],
  Luapula: [-11.2, 28.8833],
  Lusaka: [LUSAKA[0], LUSAKA[1]],
  Muchinga: [-10.55, 32.0833],
  'North-Western': [-12.1833, 26.4],
  Northern: [-10.2167, 31.1833],
  Southern: [-16.8, 26.9833],
  Western: [-15.2833, 23.1333],
};

export function facilitySeeds(country = 'ZM'): Facility[] {
  const nowIso = new Date().toISOString();
  return SEEDS.map((seed) => ({
    id: `facility-${seed.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')}`,
    name: seed.name,
    type: seed.type,
    address: seed.address,
    city: seed.city,
    province: seed.province,
    country,
    phone: null,
    emergencyPhone: null,
    latitude: seed.lat,
    longitude: seed.lng,
    services: seed.services,
    maternalServices: seed.maternalServices,
    openingHours: seed.openingHours,
    hasMaternity: seed.hasMaternity,
    has24HourEmergency: seed.has24HourEmergency,
    imageUrl: null,
    imagePublicId: null,
    verified: false,
    verifiedAt: null,
    active: true,
    createdAt: nowIso,
    updatedAt: nowIso,
  }));
}

/** Straight-line distance in km (haversine). Used only for sorting. */
export function distanceKm(a: [number, number], b: [number, number]): number {
  const R = 6371;
  const toRad = (deg: number) => (deg * Math.PI) / 180;
  const dLat = toRad(b[0] - a[0]);
  const dLng = toRad(b[1] - a[1]);
  const lat1 = toRad(a[0]);
  const lat2 = toRad(b[0]);
  const h = Math.sin(dLat / 2) ** 2 + Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLng / 2) ** 2;
  return Math.round(2 * R * Math.asin(Math.sqrt(h)));
}

/** Google Maps directions link — the app never embeds a map of its own. */
export const directionsUrl = (facility: Facility): string =>
  facility.latitude !== null && facility.longitude !== null
    ? `https://www.google.com/maps/dir/?api=1&destination=${facility.latitude},${facility.longitude}`
    : `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${facility.name} ${facility.city} Zambia`)}`;
