/**
 * Patient Reports screen.
 *
 * Displays all official healthcare clinical reports generated for this patient:
 * Antenatal summaries, clinical visit records, immunization histories, and referrals.
 *
 * Features:
 *  - Real PDF generation and download (MamaCare_Report_2026-XXXXX.pdf)
 *  - Clean PDF preview modal
 *  - Instant browser printing
 *  - Search and filter by report number, facility, report type, date
 *  - Strict privacy: only loads records for the authenticated patient.
 */

import { useEffect, useMemo, useState } from 'react';
import {
  Download,
  Eye,
  FileCheck2,
  FileText,
  Printer,
  Search,
  ShieldCheck,
} from 'lucide-react';
import { useAsync } from '@/hooks';
import { useSession } from '@/providers/app-providers';
import { healthcareReportRepo } from '@/services/repositories';
import { formatDate } from '@/lib/utils';
import { downloadHealthcareReportPdf, printHealthcareReportPdf } from '@/lib/pdf-report';
import { HEALTHCARE_REPORT_TYPE_LABELS, type HealthcareReport, type HealthcareReportType } from '@/types/domain';
import { AppShell, PageHeader } from '@/components/layout/app-shell';
import { Button } from '@/components/ui/button';
import { Card, SectionHeading } from '@/components/ui/card';
import { Badge, EmptyState, LoadingRows } from '@/components/ui/display';
import { SearchInput, Select } from '@/components/ui/form';
import { ReportPreviewModal } from '@/components/reports/report-preview-modal';

export default function PatientReportsPage() {
  const { actor } = useSession();
  const uid = actor?.uid ?? '';

  const [search, setSearch] = useState('');
  const [selectedType, setSelectedType] = useState<string>('ALL');
  const [previewReport, setPreviewReport] = useState<HealthcareReport | null>(null);

  useEffect(() => {
    document.title = 'My Healthcare Reports · Mama Care';
  }, []);

  const { data, loading, error, run } = useAsync(() => healthcareReportRepo.forPatient(uid), {
    deps: [uid],
    immediate: Boolean(uid),
  });

  const reports = useMemo<HealthcareReport[]>(() => data ?? [], [data]);

  const filtered = useMemo(() => {
    const term = search.trim().toLowerCase();
    return reports.filter((r) => {
      if (selectedType !== 'ALL' && r.reportType !== selectedType) return false;
      if (!term) return true;
      return (
        r.reportNumber.toLowerCase().includes(term) ||
        r.title.toLowerCase().includes(term) ||
        r.facilityName.toLowerCase().includes(term) ||
        (r.generatedByName && r.generatedByName.toLowerCase().includes(term))
      );
    });
  }, [reports, search, selectedType]);

  const handleDownload = (report: HealthcareReport, e: React.MouseEvent) => {
    e.stopPropagation();
    downloadHealthcareReportPdf(report);
  };

  const handlePrint = (report: HealthcareReport, e: React.MouseEvent) => {
    e.stopPropagation();
    printHealthcareReportPdf(report);
  };

  return (
    <AppShell>
      <PageHeader
        title="Official Healthcare Reports"
        description="Download, preview and print verified clinical summaries generated by your health facility."
      />

      {/* Filter & Search Bar */}
      <Card className="card-pad mb-6">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <div className="flex-1">
            <SearchInput
              placeholder="Search by report number, facility or title…"
              value={search}
              onValueChange={setSearch}
            />
          </div>

          <div className="w-full sm:w-64">
            <Select
              aria-label="Filter by report type"
              value={selectedType}
              onChange={(e) => setSelectedType(e.target.value)}
              options={[
                { value: 'ALL', label: 'All Report Types' },
                ...Object.entries(HEALTHCARE_REPORT_TYPE_LABELS).map(([val, label]) => ({
                  value: val,
                  label,
                })),
              ]}
            />
          </div>
        </div>
      </Card>

      {loading ? <LoadingRows rows={4} /> : null}

      {!loading && reports.length === 0 ? (
        <EmptyState
          icon={<FileText className="size-8 text-brand-700" aria-hidden />}
          title="No healthcare reports generated yet"
          description="When your healthcare provider conducts an antenatal check-up, clinical visit or postnatal review, official reports will be issued here with downloadable PDFs."
        />
      ) : null}

      {!loading && reports.length > 0 && filtered.length === 0 ? (
        <EmptyState
          icon={<Search className="size-8 text-ink-400" aria-hidden />}
          title="No matching reports found"
          description="Try modifying your search keywords or selecting 'All Report Types'."
        />
      ) : null}

      {!loading && filtered.length > 0 ? (
        <div className="space-y-4">
          {filtered.map((report) => (
            <Card
              key={report.id}
              className="card-pad cursor-pointer transition-shadow hover:shadow-md"
              onClick={() => setPreviewReport(report)}
            >
              <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
                <div className="flex items-start gap-3.5">
                  <div className="grid size-11 place-items-center rounded-xl bg-brand-50 text-brand-700 ring-1 ring-brand-200 shrink-0">
                    <FileCheck2 className="size-6" aria-hidden />
                  </div>
                  <div>
                    <div className="flex flex-wrap items-center gap-2">
                      <h3 className="text-base font-bold text-ink-950">{report.title}</h3>
                      <Badge tone="brand">#{report.reportNumber}</Badge>
                      <Badge tone="green">{report.status.toUpperCase()}</Badge>
                    </div>
                    <p className="mt-1 text-xs text-ink-600">
                      {report.facilityName} · Prepared by {report.generatedByName || 'Clinician'} ({report.generatedByRole})
                    </p>
                    <p className="mt-0.5 text-xs text-ink-500">
                      Issued: {report.createdAt ? formatDate(report.createdAt, 'long') : 'Recently'}
                    </p>
                  </div>
                </div>

                <div className="flex flex-wrap items-center gap-2 self-start sm:self-center">
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={(e) => {
                      e.stopPropagation();
                      setPreviewReport(report);
                    }}
                    icon={<Eye className="size-4" aria-hidden />}
                  >
                    Preview
                  </Button>
                  <Button
                    variant="secondary"
                    size="sm"
                    onClick={(e) => handlePrint(report, e)}
                    icon={<Printer className="size-4" aria-hidden />}
                  >
                    Print
                  </Button>
                  <Button
                    variant="primary"
                    size="sm"
                    onClick={(e) => handleDownload(report, e)}
                    icon={<Download className="size-4" aria-hidden />}
                  >
                    Download PDF
                  </Button>
                </div>
              </div>
            </Card>
          ))}
        </div>
      ) : null}

      {/* Report Preview Modal */}
      <ReportPreviewModal
        report={previewReport}
        open={Boolean(previewReport)}
        onClose={() => setPreviewReport(null)}
      />
    </AppShell>
  );
}
